CREATE TABLE CATEGORY (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE PERSON (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL
);

CREATE TABLE EXPENSE (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    cost BIGINT NOT NULL,
    data DATE DEFAULT CURRENT_DATE,
    category_name VARCHAR(100) NOT NULL,
    person_id BIGINT NOT NULL
);