CREATE TABLE CATEGORY (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE PERSON (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL
);

CREATE TABLE EXPENSE (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    cost BIGINT NOT NULL,
    data DATE NOT NULL DEFAULT CURRENT_DATE,
    categoryName VARCHAR(100) NOT NULL,
    personId BIGINT NOT NULL
);