insert into CATEGORY (name)
values  ('Food'),
        ('Auto'),
        ('Household chemical'),
        ('Help'),
        ('Presents'),
        ('Household appliances'),
        ('Babies'),
        ('Pets'),
        ('Health and beauty'),
        ('Credits and debts'),
        ('Invoice'),
        ('Tax and insurance'),
        ('Leisure'),
        ('Education'),
        ('Сlothes and accessories'),
        ('Renovation and furniture'),
        ('Transport'),
        ('Business'),
        ('Rest'),
        ('Investments');

